name: readability
description: "A Flutter wrapper for https://github.com/go-shiori/go-readability"
version: 0.0.2
homepage: https://git.kat.directory/SphericalKat/readability-dart

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        pluginClass: ReadabilityPlugin
        ffiPlugin: true
      # ios:
      #   pluginClass: ReadabilityPlugin
      #   ffiPlugin: true
